#!/bin/sh

set -e

case "$1" in
    remove|deconfigure|remove-in-favour|deconfigure-in-favour)
		service signal stop
        ;;
    upgrade|failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        ;;
esac



exit 0
